#!/usr/bin/env python3
"""Doc-freshness gate (`just docs`, prek hook, CI). Regenerates, then fails if anything changed.

Generated (between `<!-- BEGIN GENERATED: x -->` / `<!-- END GENERATED: x -->` markers):
  docs/decisions/README.md          ADR index                    (whole file)
  docs/ARCHITECTURE.md public-contracts  import contracts from spec/, aggregator/, collector/ pyproject.toml
  docs/ENGINEERING.md tools         tool table from standards/versions.toml
Checks: pins in versions.toml match the root pyproject dev group + dev-tools.lock; every
`just <recipe>` mentioned in CLAUDE.md / README.md / docs/ENGINEERING.md exists; no `proposed` ADR
older than 30 days; every noqa / type-ignore / shellcheck-disable carries `why:`; a branch that
changes schemas, merge or ranking also changes VERDICT-LOGIC, schemas/CHANGELOG, RANKING,
PROTOCOL or an ADR.
"""

from __future__ import annotations

import datetime as dt
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADR_DIR = ROOT / "docs" / "decisions"
TODAY = dt.datetime.now(dt.UTC).date()
PROPOSED_MAX_DAYS = 30
RULE_DOCS = (
    "docs/VERDICT-LOGIC.md",
    "schemas/CHANGELOG.md",
    "docs/decisions/",
    "docs/RANKING.md",
    "spec/PROTOCOL.md",
)
RULE_CODE = re.compile(
    r"^(schemas/[^/]+\.schema\.json|spec/schemas/[^/]+\.schema\.json"
    r"|aggregator/opc_aggregator/merge\.py|collector/opc_collector/rank\.py)$"
)
SUPPRESS = re.compile(r"#\s*(noqa\b|type:\s*ignore|pyright:\s*ignore|shellcheck\s+disable)")

errors: list[str] = []


def splice(path: Path, name: str, body: str) -> None:
    """Replace the generated block `name` in `path` with `body`."""
    text = path.read_text(encoding="utf-8")
    begin, end = f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->"
    if begin not in text or end not in text:
        errors.append(f"{path.relative_to(ROOT)}: missing generated block '{name}'")
        return
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    path.write_text(f"{head}{begin}\n{body.rstrip()}\n{end}{tail}", encoding="utf-8")


def adr_meta(p: Path) -> tuple[str, str, str, str]:
    """(number, title, status, date) of one ADR file."""
    text = p.read_text(encoding="utf-8")
    m = re.match(r"# (\d{4})\. (.+)", text)
    status = re.search(r"^- Status: (.+)$", text, re.MULTILINE)
    date = re.search(r"^- Date: (\d{4}-\d{2}-\d{2})$", text, re.MULTILINE)
    if not (m and status and date):
        errors.append(f"{p.relative_to(ROOT)}: needs '# NNNN. Title', '- Status:' and '- Date:' lines")
        return p.stem[:4], p.stem, "?", "?"
    return m.group(1), m.group(2), status.group(1).strip(), date.group(1)


def gen_adr_index() -> None:
    """docs/decisions/README.md + the proposed-age check."""
    rows = []
    for p in sorted(ADR_DIR.glob("[0-9][0-9][0-9][0-9]-*.md")):
        if p.name.startswith("0000-"):
            continue
        num, title, status, date = adr_meta(p)
        rows.append(f"| [{num}]({p.name}) | {title} | {status} | {date} |")
        if status == "proposed" and date != "?":
            age = (TODAY - dt.date.fromisoformat(date)).days
            if age > PROPOSED_MAX_DAYS:
                errors.append(
                    f"{p.name}: proposed for {age} days (> {PROPOSED_MAX_DAYS}); accept or reject it"
                )
    body = (
        "# Architecture decision records\n\n"
        "<!-- Generated by scripts/check_docs.py (`just docs`). Do not edit; edit the ADR files. -->\n\n"
        "New ADR: copy [0000-template.md](0000-template.md) to the next number, keep it to one page.\n\n"
        "| # | Decision | Status | Date |\n|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )
    (ADR_DIR / "README.md").write_text(body, encoding="utf-8")


def gen_architecture() -> None:
    """Public import contracts in docs/ARCHITECTURE.md."""
    splice(
        ROOT / "docs" / "ARCHITECTURE.md",
        "public-contracts",
        "\n".join(contracts_md(ROOT / pkg / "pyproject.toml") for pkg in ("spec", "aggregator", "collector")),
    )


def contracts_md(pyproject: Path) -> str:
    """Import contracts of one package as markdown."""
    cfg = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    out = []
    for c in cfg["tool"]["importlinter"]["contracts"]:
        out.append(f"**{c['name']}** ({c['type']})\n")
        if c["type"] == "layers":
            out += [f"{i}. `{layer}`" for i, layer in enumerate(c["layers"], 1)]
        elif c["type"] == "independence":
            out.append("- independent: " + ", ".join(f"`{m}`" for m in c["modules"]))
        else:
            out.append("- " + ", ".join(f"`{m}`" for m in c["source_modules"]))
            out.append("- may not import: " + ", ".join(f"`{m}`" for m in c["forbidden_modules"]))
        out.append("")
    return "\n".join(out)


def gen_tool_table() -> dict[str, dict[str, dict[str, str]]]:
    """docs/ENGINEERING.md tool table from standards/versions.toml; returns the parsed pins."""
    pins: dict[str, dict[str, dict[str, str]]] = tomllib.loads(
        (ROOT / "standards" / "versions.toml").read_text(encoding="utf-8")
    )
    rows = ["| Stack | Tool | Version | Job | Status |", "|---|---|---|---|---|"]
    for stack, tools in pins.items():
        rows += [f"| {stack} | {t} | {v['version']} | {v['job']} | {v['status']} |" for t, v in tools.items()]
    splice(ROOT / "docs" / "ENGINEERING.md", "tools", "\n".join(rows))
    return pins


def check_pins(pins: dict[str, dict[str, dict[str, str]]]) -> None:
    """versions.toml must agree with the dev group and dev-tools.lock."""
    group = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["dependency-groups"]
    for req in group["dev"]:
        name, _, ver = req.partition("==")
        want = pins["python"].get(name, {}).get("version")
        if want != ver:
            errors.append(f"pin drift: {name} pyproject={ver or 'unpinned'} versions.toml={want}")
    for line in (ROOT / "standards" / "dev-tools.lock").read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#"):
            name, ver = line.split()[:2]
            if pins["binaries"].get(name, {}).get("version") != ver:
                errors.append(f"pin drift: {name} dev-tools.lock={ver} versions.toml differs")


def check_recipes() -> None:
    """Every `just <recipe>` mentioned in agent/human docs must exist in the justfile."""
    text = (ROOT / "justfile").read_text(encoding="utf-8")
    recipes = set(re.findall(r"^([a-z][\w-]*)(?:\s[^:=\n]*)?:(?!=)", text, re.MULTILINE))
    for doc in ("CLAUDE.md", "README.md", "docs/ENGINEERING.md"):
        p = ROOT / doc
        if not p.exists():
            errors.append(f"{doc}: missing")
            continue
        for chunk in re.findall(r"`just ([^`]+)`", p.read_text(encoding="utf-8")):
            for name in re.findall(r"(?:^|\s)([a-z][\w-]*)", chunk):
                if name not in recipes and not name.startswith("-"):
                    errors.append(f"{doc}: `just {chunk}` names unknown recipe '{name}'")
                break  # first word is the recipe; the rest are args


def tracked(*patterns: str) -> list[str]:
    """Git ls-files for the given pathspecs."""
    out = subprocess.run(
        ["git", "ls-files", *patterns], cwd=ROOT, capture_output=True, text=True, check=False
    )
    return out.stdout.split()


def check_suppressions() -> None:
    """Noqa / type-ignore / shellcheck-disable must say why on the same line."""
    for rel in tracked("*.py", "*.sh"):
        for n, line in enumerate((ROOT / rel).read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            if SUPPRESS.search(line) and "why:" not in line:
                errors.append(f"{rel}:{n}: suppression without '# why:'")


def check_rule_docs() -> None:
    """Verdict/score/schema changes on this branch need a doc/ADR/changelog change too."""
    for base in ("origin/master", "master"):
        mb = subprocess.run(
            ["git", "merge-base", "HEAD", base], cwd=ROOT, capture_output=True, text=True, check=False
        )
        if mb.returncode == 0:
            break
    else:
        return  # no master to compare against (e.g. a shallow checkout)
    diff = subprocess.run(
        ["git", "diff", "--name-only", mb.stdout.strip()],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    ).stdout.split()
    if any(RULE_CODE.match(f) for f in diff) and not any(f.startswith(RULE_DOCS) for f in diff):
        errors.append(
            "schemas/merge/ranking changed without VERDICT-LOGIC.md, schemas/CHANGELOG.md, RANKING.md,"
            " PROTOCOL.md or an ADR"
        )


def main() -> int:
    """Regenerate, run checks, report. Exit 1 on stale generated docs or any failed check."""
    generated = [
        ADR_DIR / "README.md",
        ROOT / "docs" / "ARCHITECTURE.md",
        ROOT / "docs" / "ENGINEERING.md",
    ]
    before = {p: p.read_text(encoding="utf-8") if p.exists() else "" for p in generated}
    gen_adr_index()
    gen_architecture()
    check_pins(gen_tool_table())
    check_recipes()
    check_suppressions()
    check_rule_docs()
    errors.extend(
        f"{p.relative_to(ROOT)}: generated section was stale (now regenerated; commit it)"
        for p in generated
        if p.read_text(encoding="utf-8") != before[p]
    )
    for e in errors:
        print(f"check-docs: {e}", file=sys.stderr)
    if not errors:
        print("check-docs: ok")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
